name: GeMTC-test | push | deploy

on:
  push:
    branches: develop

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['12']
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.deployPrivateKey }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: run yarn
        run: yarn

      - name: unit tests
        id: tests
        run: yarn test

      - name: docker login
        run: docker login -u addis -p ${{ secrets.dockerRegistryPassword }}

      - name: build patavi docker image
        run: docker build --tag addis/patavi-gemtc-worker:test R/

      - name: docker push patavi
        run: docker push addis/patavi-gemtc-worker:test

      - name: build docker image
        run: ./build-docker.sh GOOGLE Test test

      - name: docker push
        run: docker push addis/gemtc:test

      - name: pull GeMTC image on server
        run: ssh -o StrictHostKeyChecking=no deploy@gemtc-test.drugis.org 'docker pull addis/gemtc:test'

      - name: pull Patavi image on server
        run: ssh -o StrictHostKeyChecking=no deploy@patavi-test.drugis.org 'docker pull addis/patavi-gemtc-worker:test'

      - name: stop Patavi docker container on the server
        run: ssh -o StrictHostKeyChecking=no deploy@patavi-test.drugis.org 'docker stop amqp-gemtc-multipart || true'

      - name: delete Patavi docker container on the server
        run: ssh -o StrictHostKeyChecking=no deploy@patavi-test.drugis.org 'docker rm amqp-gemtc-multipart || true'

      - name: stop GeMTC docker container on the server
        run: ssh -o StrictHostKeyChecking=no deploy@gemtc-test.drugis.org 'docker stop gemtc || true'

      - name: remove GeMTC container on the server
        run: ssh -o StrictHostKeyChecking=no deploy@gemtc-test.drugis.org 'docker rm gemtc || true'

      - name: update database
        run: |
          cd liquibase
          docker run --rm -v $(pwd):/liquibase/ --network host \
           -e "LIQUIBASE_URL=jdbc:postgresql://psql-test.drugis.org:5432/gemtc" \
           -e "LIQUIBASE_USERNAME=gemtc" \
           -e "LIQUIBASE_PASSWORD=${{ secrets.gemtcTestDbPassword }}" \
           -e "LIQUIBASE_CHANGELOG=liquibase-changelog.sql" \
           webdevops/liquibase:postgres update

      - name: run patavi worker container on the server
        run: >
          ssh -o StrictHostKeyChecking=no deploy@patavi-test.drugis.org \
          "docker run -d --link rabbit:rabbit \
           -e PATAVI_BROKER_HOST=rabbit \
           -e PATAVI_BROKER_USER=admin \
           -e PATAVI_BROKER_PASSWORD=${{ secrets.pataviTestBrokerPassword }} \
           --name amqp-gemtc-multipart \
           addis/patavi-gemtc-worker:test"

      - name: run GeMTC container on the server
        run: >
          ssh -o StrictHostKeyChecking=no deploy@gemtc-test.drugis.org \
          "docker run -d --name=gemtc \
           -e GEMTC_GOOGLE_KEY=${{ secrets.googleKeyTest }} \
           -e GEMTC_GOOGLE_SECRET=${{ secrets.googleSecretTest }} \
           -e GEMTC_COOKIE_SECRET=${{ secrets.cookieSecretTest }} \
           -e DB_HOST=psql-test.drugis.org \
           -e GEMTC_DB=gemtc \
           -e GEMTC_DB_HOST=psql-test.drugis.org \
           -e GEMTC_DB_USERNAME=gemtc \
           -e GEMTC_DB_PASSWORD=${{ secrets.gemtcTestDbPassword }} \
           -e PATAVI_HOST=patavi-test.drugis.org \
           -e PATAVI_PORT=443 \
           -e GEMTC_HOST=https://gemtc-test.drugis.org \
           -e SECURE_TRAFFIC=true \
           -e PATAVI_API_KEY=${{ secrets.pataviApiKeyTest }} \
           -p 8084:3001 \
           addis/gemtc:test"

      # Without sleep, prune will remove the container.
      - name: Sleep for 60 seconds
        run: sleep 60

      - name: prune docker on GeMTC server
        run: ssh -o StrictHostKeyChecking=no deploy@gemtc-test.drugis.org 'docker system prune -f'

      - name: prune docker on the patavi server
        run: ssh -o StrictHostKeyChecking=no deploy@patavi-test.drugis.org 'docker system prune -f'

      - name: docker registry garbage collection
        run: ssh -o StrictHostKeyChecking=no deploy@registry.drugis.org './garbage-collect-registry.sh'

      - name: notify on slack channel on failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.slackWebhook }}
          SLACK_USERNAME: gitbot
          SLACK_TITLE: 'Develop push:'
          SLACK_MESSAGE: 'GeMTC-test deploy failed'

      - name: notify on slack channel on success
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.slackWebhook }}
          SLACK_USERNAME: gitbot
          SLACK_TITLE: 'Develop push:'
          SLACK_MESSAGE: 'GeMTC-test deployed'
